CREATE EXTERNAL TABLE `accaci_gp_weekly_accum_tmp`(
    `source` string COMMENT 'from deserializer',
    `product_line_id` string COMMENT 'from deserializer',
    `year` string COMMENT 'from deserializer',
    `quarter` string COMMENT 'from deserializer',
    `month` string COMMENT 'from deserializer',
    `period` string COMMENT 'from deserializer',
    `sold_to_customer` string COMMENT 'from deserializer',
    `Customer` string COMMENT 'from deserializer',
    `order_type` string COMMENT 'from deserializer',
    `business_type` string COMMENT 'from deserializer',
    `product_type` string COMMENT 'from deserializer',
    `distribution` string COMMENT 'from deserializer',
    `distribution_type` string COMMENT 'from deserializer',
    `territory` string COMMENT 'from deserializer',
    `territory2` string COMMENT 'from deserializer',
    `branch` string COMMENT 'from deserializer',
    `branch2` string COMMENT 'from deserializer',
    `country_id` string COMMENT 'from deserializer',
    `country_chinese` string COMMENT 'from deserializer',
    `ou` string COMMENT 'from deserializer',
    `warranty` string COMMENT 'from deserializer',
    `csid` string COMMENT 'from deserializer',
    `part_number` string COMMENT 'from deserializer',
    `description` string COMMENT 'from deserializer',
    `all_qty` string COMMENT 'from deserializer',
    `revenue_usd_hedge_rate` string COMMENT 'from deserializer',
    `revenue_fxdiff` string COMMENT 'from deserializer',
    `net_revenue_usd_agp` string COMMENT 'from deserializer',
    `net_revenue_fxdiff` string COMMENT 'from deserializer',
    `local_cogs_amount` string COMMENT 'from deserializer',
    `local_cogs_amount_fxdiff` string COMMENT 'from deserializer',
    `credit_note_hedge_rate` string COMMENT 'from deserializer',
    `credit_note_fxdiff` string COMMENT 'from deserializer',
    `total_ship_fee_company` string COMMENT 'from deserializer',
    `total_ship_fee_company_fxdiff` string COMMENT 'from deserializer',
    `cost_period` string COMMENT 'from deserializer',
    `funding` string COMMENT 'from deserializer',
    `csc_ratio` string COMMENT 'from deserializer',
    `csc_amt` string COMMENT 'from deserializer',
    `csc_amt_fxdiff` string COMMENT 'from deserializer',
    `ship_fee_hq` string COMMENT 'from deserializer',
    `total_ship_fee_hq` string COMMENT 'from deserializer',
    `total_ship_fee` string COMMENT 'from deserializer',
    `total_ship_fee_fxdiff` string COMMENT 'from deserializer',
    `hq_asc` string COMMENT 'from deserializer',
    `hq_asc_fxdiff` string COMMENT 'from deserializer',
    `cogs_amount` string COMMENT 'from deserializer',
    `cogs_amount_fxdiff` string COMMENT 'from deserializer',
    `opp_amount` string COMMENT 'from deserializer',
    `extra_rebate` string COMMENT 'from deserializer',
    `nv_sellout_rebate` string COMMENT 'from deserializer',
    `os_incentive` string COMMENT 'from deserializer',
    `local_gp` string COMMENT 'from deserializer',
    `local_gp_fxdiff` string COMMENT 'from deserializer',
    `hq_asp` string COMMENT 'from deserializer',
    `hq_asp_fxdiff` string COMMENT 'from deserializer',
    `hq_gp_unit` string COMMENT 'from deserializer',
    `hq_gp_unit_fxdiff` string COMMENT 'from deserializer',
    `hq_gp` string COMMENT 'from deserializer',
    `hq_gp_usd_fxdiff` string COMMENT 'from deserializer',
    `hq_rev` string COMMENT 'from deserializer',
    `hq_rev_usd_fxdiff` string COMMENT 'from deserializer',
    `gp_pod` string COMMENT 'from deserializer',
    `gp_pod_fxdiff` string COMMENT 'from deserializer',
    `gp_net` string COMMENT 'from deserializer',
    `gp_net_fxdiff` string COMMENT 'from deserializer',
    `model` string COMMENT 'from deserializer',
    `segment` string COMMENT 'from deserializer',
    `gpu` string COMMENT 'from deserializer',
    `cpu_vendor` string COMMENT 'from deserializer',
    `cpu_platform` string COMMENT 'from deserializer',
    `cpu_sku` string COMMENT 'from deserializer',
    `lcd_code` string COMMENT 'from deserializer',
    `cpu_n` string COMMENT 'from deserializer',
    `acc_segment` string COMMENT 'from deserializer',
    `revenue_rmb` string COMMENT 'from deserializer',
    `net_revenue_rmb` string COMMENT 'from deserializer',
    `local_cogs_amount_rmb` string COMMENT 'from deserializer',
    `credit_note_rmb` string COMMENT 'from deserializer',
    `total_ship_fee_rmb` string COMMENT 'from deserializer',
    `cogs_amount_rmb` string COMMENT 'from deserializer',
    `opp_amount_rmb` string COMMENT 'from deserializer',
    `extra_rebate_rmb` string COMMENT 'from deserializer',
    `nv_sellout_rebate_rmb` string COMMENT 'from deserializer',
    `funding_rmb` string COMMENT 'from deserializer',
    `os_incentive_rmb` string COMMENT 'from deserializer',
    `branch_shipfee_rmb` string COMMENT 'from deserializer',
    `csc_amt_rmb` string COMMENT 'from deserializer',
    `hq_gp_rmb` string COMMENT 'from deserializer',
    `gp_pod_rmb` string COMMENT 'from deserializer',
    `gp_net_rmb` string COMMENT 'from deserializer',
    `local_gp_rmb` string COMMENT 'from deserializer'
  )
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
  'escapeChar'='\\',
  'quoteChar'='\"',
  'separatorChar' = ','
)
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 's3://consumer-npspo/StaticFiles/armourycrate/accaci_gp_weekly_accum_tmp/'
TBLPROPERTIES (
  'classification' = 'csv',
  'skip.header.line.count' = '1'
);